const productData = [
  {
    id: 1,
    name: "iPhone 17 pro",
    price: 1400000,
    description: "This is a very nice phone with 8gb ram and 512gb storage",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 2,
    name: "MacBook Pro M5",
    price: 2500000,
    description: "The latest MacBook with the new M5 chip, 16GB RAM, 1TB SSD.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 3,
    name: "Sony WH-1000XM6",
    price: 400000,
    description: "Noise-cancelling headphones with amazing sound quality.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 8,
    name: "Sonos Five",
    price: 550000,
    description: "High-fidelity speaker for music and more.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 11,
    name: "Keychron Q3",
    price: 200000,
    description: "A fully customizable mechanical keyboard.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 12,
    name: "Logitech MX Master 3S",
    price: 100000,
    description: "Advanced wireless mouse.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 13,
    name: "Razer Kiyo Pro",
    price: 200000,
    description: "A high-end webcam for streaming.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 16,
    name: "LG C3 65-inch OLED",
    price: 2500000,
    description: "The best OLED TV for movies and gaming.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 17,
    name: "Samsung HW-Q990C",
    price: 1600000,
    description: "A premium soundbar with Dolby Atmos.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 31,
    name: "Microsoft Surface Laptop 6",
    price: 1300000,
    description: "A sleek and powerful laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 32,
    name: "Bose QuietComfort Earbuds II",
    price: 300000,
    description: "The world's best noise cancellation.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 36,
    name: "Rode NT-USB+",
    price: 170000,
    description: "A studio-quality USB microphone.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 37,
    name: "Elgato Stream Deck +",
    price: 200000,
    description: "Your shortcut to seamless streaming.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 45,
    name: "Technics SL-1200GR",
    price: 1700000,
    description: "A legendary direct-drive turntable.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 47,
    name: "Devialet Phantom I",
    price: 3200000,
    description: "An ultra-high-end wireless speaker.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 51,
    name: "Samsung Galaxy S25 Ultra",
    price: 1300000,
    description: "The best Android phone money can buy.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 52,
    name: "Google Pixel 10 Pro",
    price: 1100000,
    description: "The smartest smartphone.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 53,
    name: "OnePlus 14 Pro",
    price: 900000,
    description: "Flagship killer with amazing performance.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 54,
    name: "Asus ROG Phone 9",
    price: 1200000,
    description: "The ultimate gaming phone.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 55,
    name: "Sony Xperia 1 VI",
    price: 1300000,
    description: "A phone for creators.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 56,
    name: "Nothing Phone (3)",
    price: 700000,
    description: "A phone with a unique design.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 57,
    name: "Samsung Galaxy Z Fold 7",
    price: 1800000,
    description: "The future of foldable phones.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 58,
    name: "iPhone 17",
    price: 1000000,
    description: "The standard iPhone for everyone.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 59,
    name: "Google Pixel 9a",
    price: 500000,
    description: "The best budget phone.",
    category: "phones",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 60,
    name: "Dell XPS 15",
    price: 2000000,
    description: "A stunning laptop for creators.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 61,
    name: "Razer Blade 16",
    price: 3000000,
    description: "The ultimate gaming laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 62,
    name: "HP Spectre x360 14",
    price: 1600000,
    description: "A versatile 2-in-1 laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 63,
    name: "Lenovo Yoga 9i",
    price: 1800000,
    description: "A stylish and powerful convertible.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 64,
    name: "Asus ROG Zephyrus G14",
    price: 1500000,
    description: "A portable and powerful gaming laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 65,
    name: "MacBook Air M4",
    price: 1200000,
    description: "The best laptop for everyday use.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 66,
    name: "LG Gram 17",
    price: 1700000,
    description: "An incredibly lightweight 17-inch laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 67,
    name: "Framework Laptop 13",
    price: 1400000,
    description: "A modular and repairable laptop.",
    category: "laptops",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 68,
    name: "Sennheiser HD 800 S",
    price: 1600000,
    description: "Reference-class open-back headphones.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 69,
    name: "KEF LS50 Wireless II",
    price: 2800000,
    description: "An iconic bookshelf speaker, reimagined.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 70,
    name: "Apple AirPods Max 2",
    price: 600000,
    description: "High-fidelity audio with spatial audio.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 71,
    name: "Shure SM7B",
    price: 400000,
    description: "A legendary vocal microphone.",
    category: "audio",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 72,
    name: "CalDigit TS4 Thunderbolt 4 Dock",
    price: 400000,
    description: "The ultimate docking station.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 73,
    name: "Anker 737 Power Bank",
    price: 150000,
    description: "A powerful and fast-charging power bank.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 74,
    name: "Logitech Litra Glow",
    price: 60000,
    description: "Premium streaming light.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 75,
    name: "Peak Design Everyday Backpack 20L",
    price: 260000,
    description: "A backpack for your camera and tech gear.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 76,
    name: "Grovemade Desk Shelf",
    price: 280000,
    description: "Elevate your workspace.",
    category: "accessories",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 77,
    name: "Samsung S95D 77-inch QD-OLED",
    price: 4500000,
    description: "The brightest OLED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 78,
    name: "Sony A95L 77-inch QD-OLED",
    price: 5000000,
    description: "The most accurate OLED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 79,
    name: "TCL QM8 85-inch Mini LED",
    price: 3000000,
    description: "A huge and bright TV for the money.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 80,
    name: "Hisense U8K 75-inch Mini LED",
    price: 1500000,
    description: "A great value Mini LED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 81,
    name: "Samsung The Frame 2025",
    price: 2000000,
    description: "A TV that looks like art.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 82,
    name: "LG G3 77-inch OLED",
    price: 4000000,
    description: "A gallery-design OLED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 83,
    name: "Sony X90L 85-inch LED",
    price: 2800000,
    description: "A great all-around LED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 84,
    name: "Samsung QN90D 65-inch Neo QLED",
    price: 2700000,
    description: "A bright and colorful QLED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
  {
    id: 85,
    name: "LG B3 65-inch OLED",
    price: 1700000,
    description: "An entry-level OLED TV.",
    category: "televisions",
    fontImage: "",
    images: ["", "", ""],
  },
];

export default productData;
